services:
  db:
    image: postgres:15
    container_name: ListeCourses_postgres
    restart: "no"   # Pas de redémarrage automatique pour éviter les blocages
    environment:
      POSTGRES_USER: Toum
      POSTGRES_PASSWORD: PatateSecrete
      POSTGRES_DB: ListeCoursesDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - liste_course


volumes:
  db_data:

networks:
  liste_course:
    external: true